"""empty message

Revision ID: 8048a04c770d
Revises: 1de9257ba78d
Create Date: 2025-04-23 18:37:26.689459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8048a04c770d'
down_revision = '1de9257ba78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('pilot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('pilot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
